# Generated by Django 5.2.4 on 2025-07-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_complaint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Complaint",
        ),
    ]
